# Frontend Service (LoadBalancer type)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: flash
  labels:
    app: frontend-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend-app
