# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: flash
  labels:
    app: backend-app
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: backend-app
