# Middleware Service
apiVersion: v1
kind: Service
metadata:
  name: middleware-service
  namespace: flash
  labels:
    app: middleware-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: middleware-app
